version: "3"

services:
    container-manager:
        build: ..
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - timer
            - test
        ports:
            - 3000:3000

    timer:
        container_name: test_timer
        image: lightninghacks/timer
        environment:
            TESTVAR: "stuff"
        volumes:
            - ./test-volume:/test-volume
        ports:
            - 9812:8998
    
    test:
        container_name: test_curl
        image: curlimages/curl
        command: sleep 10000000
